spring:
  h2.console:
    enabled: false
  datasource:
    url: 'jdbc:h2:mem:todo-db'
keycloak:
  auth-server-url: 'http://localhost:8180/auth'
  realm: 'TodoApp'
  resource: 'todo-spring-client'
  public-client: true